<?php

declare(strict_types=1);

require_once dirname(__DIR__) . '/app/bootstrap.php';

use App\Auth;
use App\CargoService;
use App\CorporateService;
use App\Database;

Auth::requireRole(['admin', 'dispatcher']);
$records = CargoService::all();
$cargoId = filter_var($_GET['id'] ?? null, FILTER_VALIDATE_INT);
$record = $cargoId === false ? null : CargoService::find((int) $cargoId);
$accounts = CorporateService::all();
$shipments = Database::connection()->query('SELECT id, tracking_number, origin, destination FROM shipments WHERE status NOT IN ("delivered","returned","cancelled") ORDER BY created_at DESC LIMIT 200')->fetchAll();
$statuses = CargoService::statuses(); $customs = CargoService::customsStatuses();
$staffTitle = 'Cargo operations';
require __DIR__ . '/_header.php';
?>
<div class="row g-4 mb-4"><div class="col-xl-8"><section class="staff-card"><div class="d-flex justify-content-between gap-3 mb-3"><div><h2 class="h4 mb-1">Air, sea and road cargo</h2><p class="text-muted mb-0">Documentation, customs and transport milestones in one record.</p></div><span class="staff-badge"><?= e(count($records)) ?> records</span></div><div class="table-responsive"><table class="table staff-table"><thead><tr><th>Reference</th><th>Mode / route</th><th>Status</th><th>ETA</th></tr></thead><tbody>
<?php if ($records === []): ?><tr><td colspan="4" class="text-center text-muted py-4">No cargo records yet.</td></tr><?php endif; ?>
<?php foreach ($records as $cargo): ?><tr><td><a href="<?= e(url('staff/cargo.php?id=' . $cargo['id'])) ?>"><strong><?= e($cargo['cargo_reference']) ?></strong></a><br><small><?= e($cargo['airway_or_bill_number'] ?: 'Bill not assigned') ?></small></td><td><?= e(strtoupper((string) $cargo['transport_mode'])) ?><br><small><?= e($cargo['origin_terminal']) ?> → <?= e($cargo['destination_terminal']) ?></small></td><td><span class="staff-badge"><?= e($statuses[$cargo['status']] ?? $cargo['status']) ?></span><br><small>Customs: <?= e($customs[$cargo['customs_status']] ?? $cargo['customs_status']) ?></small></td><td><?= $cargo['estimated_arrival_at'] ? e(date('j M Y', strtotime((string) $cargo['estimated_arrival_at']))) : 'Not set' ?></td></tr><?php endforeach; ?>
</tbody></table></div></section></div>
<div class="col-xl-4"><section class="staff-card"><h2 class="h4 mb-3">New cargo record</h2><form class="staff-form" method="post" action="<?= e(url('controller/router.php?action=staff.cargo.create')) ?>"><?= csrf_field() ?>
<div class="row g-3 mb-3"><div class="col-5"><label>Mode *</label><select class="form-select" name="transport_mode" required><option value="air">Air</option><option value="sea">Sea</option><option value="road">Road</option></select></div><div class="col-7"><label>Cargo type *</label><input class="form-control" name="cargo_type" placeholder="General, perishable..." required></div></div>
<div class="mb-3"><label>Origin terminal *</label><input class="form-control" name="origin_terminal" required></div><div class="mb-3"><label>Destination terminal *</label><input class="form-control" name="destination_terminal" required></div>
<div class="row g-3 mb-3"><div class="col-6"><label>Pieces *</label><input class="form-control" type="number" name="pieces" min="1" value="1" required></div><div class="col-6"><label>Incoterm</label><input class="form-control" name="incoterm" maxlength="10" placeholder="FOB"></div></div>
<div class="row g-3 mb-3"><div class="col-6"><label>Weight (kg)</label><input class="form-control" type="number" name="gross_weight_kg" min="0" step="0.01"></div><div class="col-6"><label>Volume (CBM)</label><input class="form-control" type="number" name="volume_cbm" min="0" step="0.001"></div></div>
<div class="mb-3"><label>Carrier</label><input class="form-control" name="carrier_name"></div><div class="mb-3"><label>Vessel / flight</label><input class="form-control" name="vessel_or_flight"></div><div class="mb-3"><label>Airway bill / bill of lading</label><input class="form-control" name="airway_or_bill_number"></div><div class="mb-3"><label>Container number</label><input class="form-control" name="container_number"></div>
<div class="mb-3"><label>Link shipment</label><select class="form-select" name="shipment_id"><option value="0">None</option><?php foreach ($shipments as $shipment): ?><option value="<?= e($shipment['id']) ?>"><?= e($shipment['tracking_number']) ?> · <?= e($shipment['origin']) ?> → <?= e($shipment['destination']) ?></option><?php endforeach; ?></select></div>
<div class="mb-3"><label>Corporate account</label><select class="form-select" name="corporate_account_id"><option value="0">None</option><?php foreach ($accounts as $account): ?><option value="<?= e($account['id']) ?>"><?= e($account['company_name']) ?></option><?php endforeach; ?></select></div>
<div class="mb-3"><label>Estimated departure</label><input class="form-control" type="datetime-local" name="estimated_departure_at"></div><div class="mb-4"><label>Estimated arrival</label><input class="form-control" type="datetime-local" name="estimated_arrival_at"></div><button class="staff-btn w-100" type="submit">Create cargo record</button></form></section></div></div>
<?php if ($record): $cargo = $record['cargo']; ?><div class="row g-4"><div class="col-xl-7"><section class="staff-card"><div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><span class="text-muted"><?= e($cargo['cargo_reference']) ?></span><h2 class="h3 mb-1"><?= e(strtoupper((string) $cargo['transport_mode'])) ?> · <?= e($cargo['cargo_type']) ?></h2><p class="mb-0"><?= e($cargo['origin_terminal']) ?> → <?= e($cargo['destination_terminal']) ?></p></div><span class="staff-badge align-self-start"><?= e($statuses[$cargo['status']] ?? $cargo['status']) ?></span></div><div class="row g-3 mb-4"><div class="col-md-4"><small class="text-muted">Carrier</small><p><strong><?= e($cargo['carrier_name'] ?: 'Not assigned') ?></strong></p></div><div class="col-md-4"><small class="text-muted">Vessel / flight</small><p><strong><?= e($cargo['vessel_or_flight'] ?: 'Not assigned') ?></strong></p></div><div class="col-md-4"><small class="text-muted">Customs</small><p><strong><?= e($customs[$cargo['customs_status']] ?? $cargo['customs_status']) ?></strong></p></div></div><ol class="staff-timeline"><?php foreach ($record['milestones'] as $milestone): ?><li><h3><?= e($milestone['title']) ?></h3><p class="mb-1 text-muted"><?= e($milestone['description'] ?: 'No additional note.') ?></p><small><?= e($milestone['location'] ?: 'Location not specified') ?> · <?= e(date('j M Y, g:i A', strtotime((string) $milestone['event_time']))) ?> · <?= $milestone['is_public'] ? 'Public' : 'Internal' ?></small></li><?php endforeach; ?></ol></section></div>
<div class="col-xl-5"><section class="staff-card"><h2 class="h4 mb-2">Add cargo milestone</h2><p class="text-muted">Update movement and customs clearance together.</p><form class="staff-form" method="post" action="<?= e(url('controller/router.php?action=staff.cargo.milestone')) ?>"><?= csrf_field() ?><input type="hidden" name="cargo_id" value="<?= e($cargo['id']) ?>"><div class="mb-3"><label>Status *</label><select class="form-select" name="status" required><?php foreach ($statuses as $value => $label): ?><option value="<?= e($value) ?>" <?= $cargo['status'] === $value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><div class="mb-3"><label>Customs status *</label><select class="form-select" name="customs_status" required><?php foreach ($customs as $value => $label): ?><option value="<?= e($value) ?>" <?= $cargo['customs_status'] === $value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><div class="mb-3"><label>Milestone title</label><input class="form-control" name="title"></div><div class="mb-3"><label>Location</label><input class="form-control" name="location"></div><div class="mb-3"><label>Event time *</label><input class="form-control" type="datetime-local" name="event_time" value="<?= e(date('Y-m-d\TH:i')) ?>" required></div><div class="mb-3"><label>Description</label><textarea class="form-control" name="description"></textarea></div><div class="form-check mb-4"><input class="form-check-input" type="checkbox" name="is_public" id="cargo-public" value="1" checked><label class="form-check-label" for="cargo-public">Public milestone</label></div><button class="staff-btn" type="submit">Save milestone</button></form></section></div></div><?php endif; ?>
<?php require __DIR__ . '/_footer.php'; ?>
