<?php

declare(strict_types=1);

require_once dirname(__DIR__) . '/app/bootstrap.php';

use App\Auth;
use App\PricingService;

Auth::requireRole(['admin']);
$zones = PricingService::zones();
$services = PricingService::services();
$rates = PricingService::allRates();
$staffTitle = 'Rate management';
require __DIR__ . '/_header.php';
?>
<section class="staff-card mb-4"><div class="mb-4"><h2 class="h4 mb-1">Configure calculator rate</h2><p class="text-muted mb-0">Saving the same origin, destination and service updates that route. No default price is invented.</p></div><form class="staff-form" method="post" action="<?= e(url('controller/router.php?action=staff.rate.save')) ?>"><?= csrf_field() ?><div class="row g-3"><div class="col-md-4"><label for="rate-origin">Origin</label><select class="form-select" id="rate-origin" name="origin_zone_id" required><option value="">Choose zone</option><?php foreach ($zones as $zone): ?><option value="<?= e($zone['id']) ?>"><?= e($zone['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label for="rate-destination">Destination</label><select class="form-select" id="rate-destination" name="destination_zone_id" required><option value="">Choose zone</option><?php foreach ($zones as $zone): ?><option value="<?= e($zone['id']) ?>"><?= e($zone['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label for="rate-service">Service</label><select class="form-select" id="rate-service" name="service_code" required><option value="">Choose service</option><?php foreach ($services as $code => $name): ?><option value="<?= e($code) ?>"><?= e($name) ?></option><?php endforeach; ?></select></div>
<?php foreach (['base_fee' => 'Base fee','base_weight_kg' => 'Base weight (kg)','extra_kg_fee' => 'Extra kg fee','minimum_fee' => 'Minimum fee','packaging_fee' => 'Packaging fee'] as $field => $label): ?><div class="col-md-4 col-xl"><label for="rate-<?= e($field) ?>"><?= e($label) ?></label><input class="form-control" type="number" id="rate-<?= e($field) ?>" name="<?= e($field) ?>" min="<?= $field === 'base_weight_kg' ? '0.01' : '0' ?>" step="0.01" value="<?= $field === 'base_weight_kg' ? '1' : '0' ?>" required></div><?php endforeach; ?>
<?php foreach (['fuel_percent' => 'Fuel %','insurance_percent' => 'Insurance %','tax_percent' => 'Tax %'] as $field => $label): ?><div class="col-md-3"><label for="rate-<?= e($field) ?>"><?= e($label) ?></label><input class="form-control" type="number" id="rate-<?= e($field) ?>" name="<?= e($field) ?>" min="0" max="100" step="0.001" value="0" required></div><?php endforeach; ?><div class="col-md-3"><label for="rate-divisor">Volumetric divisor</label><input class="form-control" type="number" id="rate-divisor" name="volumetric_divisor" min="1" step="0.01" value="5000" required></div><div class="col-md-3"><label for="rate-days-min">Days minimum</label><input class="form-control" type="number" id="rate-days-min" name="estimated_days_min" min="0" max="365"></div><div class="col-md-3"><label for="rate-days-max">Days maximum</label><input class="form-control" type="number" id="rate-days-max" name="estimated_days_max" min="0" max="365"></div><div class="col-md-3"><label for="rate-currency">Currency</label><select class="form-select" id="rate-currency" name="currency"><option>NGN</option><option>USD</option><option>GBP</option><option>EUR</option></select></div><div class="col-md-3"><label for="rate-status">Status</label><select class="form-select" id="rate-status" name="status"><option value="active">Active</option><option value="inactive">Inactive</option></select></div><div class="col-12"><button class="staff-btn" type="submit"><i class="bi bi-save"></i> Save rate card</button></div></div></form></section>
<section class="staff-card"><div class="mb-3"><h2 class="h4 mb-1">Configured rates</h2><p class="text-muted mb-0">Amounts shown here drive the public calculator and online booking.</p></div><div class="table-responsive"><table class="table staff-table"><thead><tr><th>Route</th><th>Service</th><th>Base</th><th>Extra kg</th><th>Adjustments</th><th>Delivery</th><th>Status</th></tr></thead><tbody><?php if ($rates === []): ?><tr><td colspan="7" class="text-center text-muted py-4">No rates configured. The calculator will direct customers to a manual quote until an active rate exists.</td></tr><?php endif; ?><?php foreach ($rates as $rate): ?><tr><td><?= e($rate['origin_name']) ?> → <?= e($rate['destination_name']) ?></td><td><?= e($rate['service_name']) ?></td><td><?= e($rate['currency']) ?> <?= e(number_format((float) $rate['base_fee'], 2)) ?> / <?= e($rate['base_weight_kg']) ?> kg</td><td><?= e(number_format((float) $rate['extra_kg_fee'], 2)) ?></td><td><small>Fuel <?= e($rate['fuel_percent']) ?>% · Insurance <?= e($rate['insurance_percent']) ?>% · Tax <?= e($rate['tax_percent']) ?>%</small></td><td><?= $rate['estimated_days_min'] === null ? 'Not set' : e($rate['estimated_days_min'] . '–' . $rate['estimated_days_max'] . ' days') ?></td><td><span class="staff-badge"><?= e(ucfirst((string) $rate['status'])) ?></span></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php require __DIR__ . '/_footer.php'; ?>
