<?php

declare(strict_types=1);

require_once dirname(__DIR__) . '/app/bootstrap.php';

use App\Auth;
use App\ReportService;
use App\ShipmentService;

Auth::requireRole(['admin', 'dispatcher']);
$report = ReportService::dashboard($_GET['from'] ?? null, $_GET['to'] ?? null, (string) ($_GET['currency'] ?? 'NGN'));
$metrics = $report['metrics']; $labels = ShipmentService::statuses();
$maxValue = max(1, ...array_column($report['daily'], 'booking_value'));
$query = http_build_query(['from' => $report['range']['from'], 'to' => $report['range']['to'], 'currency' => $report['currency']]);
$staffTitle = 'Reports and analytics';
require __DIR__ . '/_header.php';
?>
<section class="staff-card mb-4"><form class="report-filters" method="get"><div><label for="report-from">From</label><input class="form-control" type="date" id="report-from" name="from" value="<?= e($report['range']['from']) ?>"></div><div><label for="report-to">To</label><input class="form-control" type="date" id="report-to" name="to" value="<?= e($report['range']['to']) ?>"></div><div><label for="report-currency">Reporting currency</label><select class="form-select" id="report-currency" name="currency"><?php foreach (['NGN','USD','GBP','EUR'] as $option): ?><option <?= $report['currency'] === $option ? 'selected' : '' ?>><?= e($option) ?></option><?php endforeach; ?></select></div><button class="staff-btn" type="submit">Apply filters</button><a class="staff-btn light" href="<?= e(url('staff/report-export.php?' . $query)) ?>"><i class="bi bi-download"></i> Export CSV</a></form><p class="small text-muted mt-3 mb-0">Range is capped at 366 days. Financial totals are shown only in <?= e($report['currency']) ?>; currencies are never combined. Refreshed <?= e(date('j M Y, g:i:s A', strtotime((string) $report['generated_at']))) ?>.</p></section>
<div class="row g-4 mb-4"><div class="col-sm-6 col-xl-3"><div class="staff-card stat-card"><span>Booking volume</span><strong><?= e($metrics['bookings']) ?></strong><small>Created in range</small></div></div><div class="col-sm-6 col-xl-3"><div class="staff-card stat-card"><span>Booking value</span><strong class="money-value"><?= e($report['currency']) ?> <?= e(number_format((float) $metrics['booking_value'], 0)) ?></strong><small>Cancelled bookings excluded</small></div></div><div class="col-sm-6 col-xl-3"><div class="staff-card stat-card"><span>Collected</span><strong class="money-value"><?= e($report['currency']) ?> <?= e(number_format((float) $metrics['collections'], 0)) ?></strong><small>Verified + posted payments</small></div></div><div class="col-sm-6 col-xl-3"><div class="staff-card stat-card"><span>Shipments created</span><strong><?= e($metrics['shipments']) ?></strong><small><?= e($metrics['delivered']) ?> delivered in range</small></div></div></div>
<div class="row g-4 mb-4"><div class="col-xl-8"><section class="staff-card"><div class="mb-4"><h2 class="h4 mb-1">Daily booking value</h2><p class="text-muted mb-0">Non-cancelled booking value by creation date in <?= e($report['currency']) ?>.</p></div><div class="report-bars"><?php foreach ($report['daily'] as $day): ?><div class="report-bar-row"><time><?= e(date('D, j M', strtotime((string) $day['day']))) ?></time><div><span style="width:<?= e(round(((float) $day['booking_value'] / $maxValue) * 100, 1)) ?>%"></span></div><strong><?= e(number_format((float) $day['booking_value'], 0)) ?></strong></div><?php endforeach; ?></div></section></div>
<div class="col-xl-4"><section class="staff-card mb-4"><h2 class="h4 mb-3">Shipment status mix</h2><?php $statusTotal = max(1, array_sum(array_map(static fn (array $row): int => (int) $row['total'], $report['shipment_statuses']))); foreach ($report['shipment_statuses'] as $status): ?><div class="mix-row"><span><?= e($labels[$status['status']] ?? ucwords(str_replace('_', ' ', (string) $status['status']))) ?></span><div><i style="width:<?= e(round(((int) $status['total'] / $statusTotal) * 100, 1)) ?>%"></i></div><strong><?= e($status['total']) ?></strong></div><?php endforeach; ?></section><section class="staff-card"><h2 class="h4 mb-3">Operational queue</h2><div class="watch-value"><span>Active shipments</span><strong><?= e($metrics['active_shipments']) ?></strong></div><div class="watch-value"><span>Unassigned active</span><strong><?= e($metrics['unassigned_shipments']) ?></strong></div><div class="watch-value"><span>Available riders</span><strong><?= e($metrics['available_riders']) ?></strong></div><div class="watch-value"><span>Corporate outstanding</span><strong><?= e($report['currency']) ?> <?= e(number_format((float) $metrics['corporate_outstanding'], 2)) ?></strong></div></section></div></div>
<div class="row g-4 mb-4"><div class="col-xl-5"><section class="staff-card h-100"><h2 class="h4 mb-3">Managed logistics activity</h2><div class="watch-value"><span>Bulk batches in range</span><strong><?= e($metrics['bulk_batches']) ?></strong></div><div class="watch-value"><span>Cargo records in range</span><strong><?= e($metrics['cargo_created']) ?></strong></div><div class="watch-value"><span>Active cargo now</span><strong><?= e($metrics['active_cargo']) ?></strong></div></section></div><div class="col-xl-7"><section class="staff-card h-100"><h2 class="h4 mb-3">Cargo mode and status in range</h2><div class="table-responsive"><table class="table staff-table"><thead><tr><th>Mode</th><th>Status</th><th>Records</th></tr></thead><tbody><?php if ($report['cargo_mix'] === []): ?><tr><td colspan="3" class="text-center text-muted py-4">No cargo records were created in this range.</td></tr><?php endif; ?><?php foreach ($report['cargo_mix'] as $cargo): ?><tr><td><?= e(strtoupper((string) $cargo['transport_mode'])) ?></td><td><?= e(ucwords(str_replace('_', ' ', (string) $cargo['status']))) ?></td><td><?= e($cargo['total']) ?></td></tr><?php endforeach; ?></tbody></table></div></section></div></div>
<section class="staff-card"><h2 class="h4 mb-1">Metric definitions</h2><p class="text-muted">Booking volume/value uses <code>bookings.created_at</code>. Collections use verified paid gateway transactions plus staff-posted corporate payment credits. Shipment, bulk and cargo creation use their own creation timestamps; delivery uses the latest shipment status timestamp. Current queues and outstanding credit are point-in-time values.</p></section>
<?php require __DIR__ . '/_footer.php'; ?>
