CREATE TABLE IF NOT EXISTS customer_users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    email_verified_at DATETIME NULL,
    last_login_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_customer_users_email (email),
    KEY idx_customer_users_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS customer_login_attempts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    email VARCHAR(190) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    was_successful TINYINT(1) NOT NULL DEFAULT 0,
    attempted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_customer_login_window (email, ip_address, was_successful, attempted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS customer_addresses (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_id BIGINT UNSIGNED NOT NULL,
    label VARCHAR(80) NOT NULL,
    recipient_name VARCHAR(120) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    address_line VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state_name VARCHAR(100) NOT NULL,
    country_code CHAR(2) NOT NULL DEFAULT 'NG',
    directions VARCHAR(500) NULL,
    is_default TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_customer_addresses_customer (customer_id, is_default),
    CONSTRAINT fk_addresses_customer FOREIGN KEY (customer_id) REFERENCES customer_users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rate_zones (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(120) NOT NULL,
    country_code CHAR(2) NOT NULL DEFAULT 'NG',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_rate_zones_code (code),
    KEY idx_rate_zones_status_name (status, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO rate_zones (code, name, country_code, status) VALUES
    ('LAGOS', 'Lagos', 'NG', 'active'),
    ('OGUN', 'Ogun State', 'NG', 'active'),
    ('ABUJA', 'Abuja FCT', 'NG', 'active'),
    ('OTHER_NIGERIA', 'Other Nigeria', 'NG', 'active'),
    ('INTERNATIONAL', 'International destination', 'ZZ', 'active');

CREATE TABLE IF NOT EXISTS rate_cards (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    origin_zone_id BIGINT UNSIGNED NOT NULL,
    destination_zone_id BIGINT UNSIGNED NOT NULL,
    service_code VARCHAR(40) NOT NULL,
    service_name VARCHAR(80) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'NGN',
    base_fee DECIMAL(14,2) NOT NULL,
    base_weight_kg DECIMAL(10,2) NOT NULL DEFAULT 1.00,
    extra_kg_fee DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    minimum_fee DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    fuel_percent DECIMAL(7,3) NOT NULL DEFAULT 0.000,
    insurance_percent DECIMAL(7,3) NOT NULL DEFAULT 0.000,
    packaging_fee DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    tax_percent DECIMAL(7,3) NOT NULL DEFAULT 0.000,
    volumetric_divisor DECIMAL(10,2) NOT NULL DEFAULT 5000.00,
    estimated_days_min SMALLINT UNSIGNED NULL,
    estimated_days_max SMALLINT UNSIGNED NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_rate_route_service (origin_zone_id, destination_zone_id, service_code),
    KEY idx_rate_cards_status (status),
    CONSTRAINT fk_rates_origin FOREIGN KEY (origin_zone_id) REFERENCES rate_zones (id),
    CONSTRAINT fk_rates_destination FOREIGN KEY (destination_zone_id) REFERENCES rate_zones (id),
    CONSTRAINT fk_rates_staff FOREIGN KEY (created_by) REFERENCES staff_users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    booking_number VARCHAR(30) NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    origin_zone_id BIGINT UNSIGNED NOT NULL,
    destination_zone_id BIGINT UNSIGNED NOT NULL,
    pickup_address_id BIGINT UNSIGNED NOT NULL,
    delivery_address_id BIGINT UNSIGNED NOT NULL,
    pickup_snapshot_json JSON NOT NULL,
    delivery_snapshot_json JSON NOT NULL,
    service_code VARCHAR(40) NOT NULL,
    service_name VARCHAR(80) NOT NULL,
    package_description VARCHAR(500) NOT NULL,
    weight_kg DECIMAL(10,2) NOT NULL,
    length_cm DECIMAL(10,2) NULL,
    width_cm DECIMAL(10,2) NULL,
    height_cm DECIMAL(10,2) NULL,
    volumetric_weight_kg DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    chargeable_weight_kg DECIMAL(10,2) NOT NULL,
    declared_value DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    is_fragile TINYINT(1) NOT NULL DEFAULT 0,
    packaging_required TINYINT(1) NOT NULL DEFAULT 0,
    currency CHAR(3) NOT NULL DEFAULT 'NGN',
    base_amount DECIMAL(14,2) NOT NULL,
    weight_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    fuel_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    insurance_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    packaging_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    tax_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(14,2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'awaiting_payment',
    payment_status VARCHAR(20) NOT NULL DEFAULT 'unpaid',
    shipment_id BIGINT UNSIGNED NULL,
    quote_expires_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_bookings_number (booking_number),
    UNIQUE KEY uq_bookings_shipment (shipment_id),
    KEY idx_bookings_customer_created (customer_id, created_at),
    KEY idx_bookings_status_created (status, created_at),
    CONSTRAINT fk_bookings_customer FOREIGN KEY (customer_id) REFERENCES customer_users (id),
    CONSTRAINT fk_bookings_origin FOREIGN KEY (origin_zone_id) REFERENCES rate_zones (id),
    CONSTRAINT fk_bookings_destination FOREIGN KEY (destination_zone_id) REFERENCES rate_zones (id),
    CONSTRAINT fk_bookings_pickup FOREIGN KEY (pickup_address_id) REFERENCES customer_addresses (id),
    CONSTRAINT fk_bookings_delivery FOREIGN KEY (delivery_address_id) REFERENCES customer_addresses (id),
    CONSTRAINT fk_bookings_shipment FOREIGN KEY (shipment_id) REFERENCES shipments (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS booking_status_history (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    booking_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(30) NOT NULL,
    note VARCHAR(500) NULL,
    actor_type VARCHAR(20) NOT NULL,
    actor_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_booking_history (booking_id, created_at),
    CONSTRAINT fk_booking_history_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    booking_id BIGINT UNSIGNED NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    provider VARCHAR(30) NOT NULL DEFAULT 'paystack',
    reference VARCHAR(50) NOT NULL,
    provider_transaction_id VARCHAR(40) NULL,
    amount DECIMAL(14,2) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'NGN',
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    authorization_url VARCHAR(500) NULL,
    access_code VARCHAR(120) NULL,
    gateway_response VARCHAR(500) NULL,
    paid_at DATETIME NULL,
    verified_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_payments_reference (reference),
    KEY idx_payments_booking_status (booking_id, status),
    KEY idx_payments_customer_created (customer_id, created_at),
    CONSTRAINT fk_payments_booking FOREIGN KEY (booking_id) REFERENCES bookings (id),
    CONSTRAINT fk_payments_customer FOREIGN KEY (customer_id) REFERENCES customer_users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_webhook_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    provider VARCHAR(30) NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    reference VARCHAR(50) NULL,
    payload_json JSON NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'received',
    error_message VARCHAR(500) NULL,
    received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_webhook_payload (provider, payload_hash),
    KEY idx_webhook_reference (provider, reference)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS billing_documents (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    booking_id BIGINT UNSIGNED NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    document_number VARCHAR(40) NOT NULL,
    document_type VARCHAR(20) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'NGN',
    subtotal DECIMAL(14,2) NOT NULL,
    tax_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(14,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'issued',
    issued_at DATETIME NOT NULL,
    paid_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_billing_documents_number (document_number),
    UNIQUE KEY uq_billing_booking_type (booking_id, document_type),
    KEY idx_billing_customer_issued (customer_id, issued_at),
    CONSTRAINT fk_billing_booking FOREIGN KEY (booking_id) REFERENCES bookings (id),
    CONSTRAINT fk_billing_customer FOREIGN KEY (customer_id) REFERENCES customer_users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notification_outbox (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_id BIGINT UNSIGNED NULL,
    booking_id BIGINT UNSIGNED NULL,
    shipment_id BIGINT UNSIGNED NULL,
    channel VARCHAR(20) NOT NULL,
    recipient VARCHAR(190) NOT NULL,
    template_code VARCHAR(80) NOT NULL,
    subject VARCHAR(190) NULL,
    message TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    next_attempt_at DATETIME NULL,
    last_error VARCHAR(500) NULL,
    sent_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_notifications_dispatch (status, next_attempt_at, created_at),
    KEY idx_notifications_customer (customer_id, created_at),
    CONSTRAINT fk_notifications_customer FOREIGN KEY (customer_id) REFERENCES customer_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_notifications_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE SET NULL,
    CONSTRAINT fk_notifications_shipment FOREIGN KEY (shipment_id) REFERENCES shipments (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS proofs_of_delivery (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    shipment_id BIGINT UNSIGNED NOT NULL,
    recipient_name VARCHAR(120) NOT NULL,
    delivery_note VARCHAR(1000) NULL,
    photo_path VARCHAR(255) NULL,
    photo_mime VARCHAR(80) NULL,
    latitude DECIMAL(10,7) NULL,
    longitude DECIMAL(10,7) NULL,
    delivered_at DATETIME NOT NULL,
    captured_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_pod_shipment (shipment_id),
    CONSTRAINT fk_pod_shipment FOREIGN KEY (shipment_id) REFERENCES shipments (id) ON DELETE CASCADE,
    CONSTRAINT fk_pod_staff FOREIGN KEY (captured_by) REFERENCES staff_users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
