<?php

declare(strict_types=1);

require_once dirname(__DIR__) . '/app/bootstrap.php';

use App\Auth;
use App\ProofOfDeliveryService;
use App\RiderService;
use App\ShipmentService;

Auth::requireRole(['rider']);
$assignments = RiderService::assignmentsForStaff((int) Auth::id());
$selectedId = filter_var($_GET['shipment'] ?? ($assignments[0]['shipment_id'] ?? null), FILTER_VALIDATE_INT);
$record = null;
if ($selectedId !== false && $selectedId !== null && RiderService::canAccessShipment((int) Auth::id(), (int) $selectedId)) {
    $record = ShipmentService::find((int) $selectedId);
}
$user = Auth::user();
$statuses = ShipmentService::statuses();
$nextStatuses = $record ? ShipmentService::allowedNextStatuses((string) $record['shipment']['status']) : [];
unset($nextStatuses['delivered']);
$proof = $record ? ProofOfDeliveryService::findByShipment((int) $record['shipment']['id']) : null;
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Rider workspace | Easyway Logistics</title><link rel="icon" href="<?= e(url('assets/img/easyway/logo.jpg')) ?>" type="image/jpeg"><link rel="stylesheet" href="<?= e(url('assets/css/bootstrap.min.css')) ?>"><link rel="stylesheet" href="<?= e(url('assets/css/bootstrap-icons.css')) ?>"><link rel="stylesheet" href="<?= e(url('assets/css/staff.css')) ?>"></head>
<body class="staff-body"><header class="rider-topbar"><a href="<?= e(url('rider/index.php')) ?>"><img src="<?= e(url('assets/img/easyway/logo.jpg')) ?>" alt="Easyway Logistics"></a><div><strong><?= e($user['name'] ?? '') ?></strong><span>Rider workspace</span></div><form method="post" action="<?= e(url('controller/router.php?action=staff.logout')) ?>"><?= csrf_field() ?><button class="staff-btn light" type="submit">Sign out</button></form></header>
<main class="rider-main"><?= flash_markup() ?><section class="rider-welcome"><div><span>Today’s route</span><h1>Deliver safely. Keep every handoff visible.</h1><p>Location sharing is always your choice and stops automatically when the assignment is completed or removed.</p></div><span class="staff-badge"><?= e(count($assignments)) ?> active assignment<?= count($assignments) === 1 ? '' : 's' ?></span></section>
<?php if ($assignments === []): ?><section class="staff-card text-center py-5"><i class="bi bi-check2-circle fs-1 text-success"></i><h2 class="h4 mt-3">You are currently unassigned</h2><p class="text-muted mb-0">Dispatch will place the next shipment here when it is ready.</p></section><?php endif; ?>
<?php if ($record): $shipment = $record['shipment']; ?><div class="row g-4"><div class="col-xl-7"><section class="staff-card mb-4"><div class="d-flex flex-wrap justify-content-between gap-3"><div><span class="text-muted">Assigned shipment</span><h2 class="h3 mb-1"><?= e($shipment['tracking_number']) ?></h2><p class="mb-0"><?= e($shipment['origin']) ?> → <?= e($shipment['destination']) ?></p></div><span class="staff-badge align-self-start"><?= e($statuses[$shipment['status']] ?? $shipment['status']) ?></span></div><hr><div class="row g-3"><div class="col-md-6"><small class="text-muted">Recipient</small><p><strong><?= e($shipment['customer_name']) ?></strong><br><a href="tel:<?= e(preg_replace('/[^+0-9]/', '', (string) $shipment['customer_phone'])) ?>"><?= e($shipment['customer_phone']) ?></a></p></div><div class="col-md-6"><small class="text-muted">Package</small><p><strong><?= e($shipment['package_description']) ?></strong><?= $shipment['weight_kg'] ? '<br>' . e($shipment['weight_kg']) . ' kg' : '' ?></p></div></div><a class="staff-btn light" target="_blank" href="https://www.google.com/maps/search/?api=1&amp;query=<?= e(rawurlencode((string) $shipment['destination'])) ?>"><i class="bi bi-map"></i> Open destination map</a></section>
<section class="staff-card"><h2 class="h4 mb-3">Shipment history</h2><ol class="staff-timeline"><?php foreach ($record['events'] as $event): ?><li><h3><?= e($event['title']) ?></h3><p class="mb-1 text-muted"><?= e($event['description'] ?: 'No additional note.') ?></p><small><?= e($event['location'] ?: 'Location not specified') ?> · <?= e(date('j M Y, g:i A', strtotime((string) $event['event_time']))) ?></small></li><?php endforeach; ?></ol></section></div>
<div class="col-xl-5"><section class="staff-card mb-4 live-control" data-rider-tracking data-endpoint="<?= e(url('api/rider/location.php')) ?>" data-shipment="<?= e($shipment['id']) ?>" data-token="<?= e(\App\Csrf::token()) ?>"><div class="d-flex align-items-center justify-content-between gap-3"><div><h2 class="h4 mb-1">Live tracking</h2><p class="text-muted mb-0">Your device sends a location about every 15 seconds.</p></div><span class="live-dot" aria-hidden="true"></span></div><div class="form-check form-switch my-4"><input class="form-check-input" type="checkbox" role="switch" id="share-public" checked><label class="form-check-label" for="share-public">Share this trip on public tracking</label></div><div class="d-grid gap-2"><button class="staff-btn" type="button" data-live-start><i class="bi bi-broadcast-pin"></i> Start location sharing</button><button class="staff-btn light" type="button" data-live-stop disabled>Stop sharing</button></div><p class="small mt-3 mb-0" data-live-status aria-live="polite">Sharing is off.</p></section>
<?php if ($shipment['status'] === 'out_for_delivery' && $proof === null): ?><section class="staff-card mb-4"><h2 class="h4 mb-2">Complete delivery</h2><p class="text-muted">Record who received the item. A delivery photo is optional and stored privately.</p><form class="staff-form" method="post" enctype="multipart/form-data" action="<?= e(url('controller/router.php?action=rider.pod.create')) ?>"><?= csrf_field() ?><input type="hidden" name="shipment_id" value="<?= e($shipment['id']) ?>"><div class="mb-3"><label>Received by *</label><input class="form-control" name="recipient_name" required></div><div class="mb-3"><label>Delivery time *</label><input class="form-control" type="datetime-local" name="delivered_at" value="<?= e(date('Y-m-d\TH:i')) ?>" required></div><div class="mb-3"><label>Delivery note</label><textarea class="form-control" name="delivery_note"></textarea></div><div class="mb-3"><label>Delivery photo</label><input class="form-control" type="file" name="delivery_photo" accept="image/jpeg,image/png,image/webp"></div><div class="row g-3 mb-4"><div class="col-6"><label>Latitude</label><input class="form-control" type="number" name="latitude" min="-90" max="90" step="0.0000001"></div><div class="col-6"><label>Longitude</label><input class="form-control" type="number" name="longitude" min="-180" max="180" step="0.0000001"></div></div><button class="staff-btn w-100" type="submit">Save proof and complete</button></form></section><?php endif; ?>
<section class="staff-card"><h2 class="h4 mb-2">Update milestone</h2><?php if ($nextStatuses === []): ?><p class="text-muted mb-0">No rider milestone is available for this shipment.</p><?php else: ?><form class="staff-form" method="post" action="<?= e(url('controller/router.php?action=rider.shipment.event')) ?>"><?= csrf_field() ?><input type="hidden" name="shipment_id" value="<?= e($shipment['id']) ?>"><div class="mb-3"><label>New status *</label><select class="form-select" name="status" required><option value="">Choose status</option><?php foreach ($nextStatuses as $value => $label): ?><option value="<?= e($value) ?>"><?= e($label) ?></option><?php endforeach; ?></select></div><div class="mb-3"><label>Current location</label><input class="form-control" name="location"></div><div class="mb-3"><label>Event time *</label><input class="form-control" type="datetime-local" name="event_time" value="<?= e(date('Y-m-d\TH:i')) ?>" required></div><div class="mb-4"><label>Delivery note</label><textarea class="form-control" name="description"></textarea></div><button class="staff-btn w-100" type="submit">Save milestone</button></form><?php endif; ?></section></div></div><?php endif; ?></main>
<script src="<?= e(url('assets/js/rider-tracking.js')) ?>" defer></script></body></html>
