<?php

declare(strict_types=1);

require_once dirname(__DIR__) . '/app/bootstrap.php';

use App\AddressService;
use App\CustomerAuth;
use App\PricingService;

CustomerAuth::requireCustomer();
$addresses = AddressService::allForCustomer((int) CustomerAuth::id());
$zones = PricingService::zones();
$services = PricingService::services();
$state = pull_form_state('booking');
$pageTitle = 'Book a Shipment';
require dirname(__DIR__) . '/app/views/partials/public-header.php';
?>
<section class="account-heading compact"><div class="container"><div><span class="page-eyebrow">Online booking</span><h1>Book with a verified rate.</h1><p>Your amount is calculated again on the server and held for 48 hours.</p></div></div></section>
<section class="account-section"><div class="container"><?php require __DIR__ . '/_nav.php'; ?><?php if (count($addresses) < 2): ?><div class="alert alert-warning">Add at least two saved addresses before booking. <a href="<?= e(url('customer/addresses.php#new-address')) ?>">Manage addresses</a>.</div><?php endif; ?><div class="easy-form-card"><form method="post" action="<?= e(url('controller/router.php?action=booking.create')) ?>" novalidate><?= csrf_field() ?><div class="booking-section"><span>1</span><div><h2>Route and addresses</h2><p>Select the physical addresses and the matching pricing zones.</p></div></div><div class="row g-3 mb-5"><div class="col-md-6"><label for="book-pickup">Pickup address</label><select class="form-select" id="book-pickup" name="pickup_address_id" required><option value="">Choose address</option><?php foreach ($addresses as $address): ?><option value="<?= e($address['id']) ?>" <?= form_value($state, 'pickup_address_id') === (string) $address['id'] ? 'selected' : '' ?>><?= e($address['label']) ?> — <?= e($address['city']) ?></option><?php endforeach; ?></select><?= form_error($state, 'pickup_address_id') ?></div><div class="col-md-6"><label for="book-delivery">Delivery address</label><select class="form-select" id="book-delivery" name="delivery_address_id" required><option value="">Choose address</option><?php foreach ($addresses as $address): ?><option value="<?= e($address['id']) ?>" <?= form_value($state, 'delivery_address_id') === (string) $address['id'] ? 'selected' : '' ?>><?= e($address['label']) ?> — <?= e($address['city']) ?></option><?php endforeach; ?></select><?= form_error($state, 'delivery_address_id') ?></div><div class="col-md-6"><label for="book-origin">Origin pricing zone</label><select class="form-select" id="book-origin" name="origin_zone_id" required><option value="">Choose zone</option><?php foreach ($zones as $zone): ?><option value="<?= e($zone['id']) ?>" <?= form_value($state, 'origin_zone_id') === (string) $zone['id'] ? 'selected' : '' ?>><?= e($zone['name']) ?></option><?php endforeach; ?></select><?= form_error($state, 'origin_zone_id') ?></div><div class="col-md-6"><label for="book-destination">Destination pricing zone</label><select class="form-select" id="book-destination" name="destination_zone_id" required><option value="">Choose zone</option><?php foreach ($zones as $zone): ?><option value="<?= e($zone['id']) ?>" <?= form_value($state, 'destination_zone_id') === (string) $zone['id'] ? 'selected' : '' ?>><?= e($zone['name']) ?></option><?php endforeach; ?></select><?= form_error($state, 'destination_zone_id') ?></div></div>
<div class="booking-section"><span>2</span><div><h2>Package and service</h2><p>Dimensions are optional, but improve volumetric-weight accuracy.</p></div></div><div class="row g-3"><div class="col-md-7"><label for="book-service">Service</label><select class="form-select" id="book-service" name="service_code" required><option value="">Choose service</option><?php foreach ($services as $code => $name): ?><option value="<?= e($code) ?>" <?= form_value($state, 'service_code') === $code ? 'selected' : '' ?>><?= e($name) ?></option><?php endforeach; ?></select><?= form_error($state, 'service_code') ?></div><div class="col-md-5"><label for="book-weight">Actual weight (kg)</label><input class="form-control" type="number" id="book-weight" name="weight_kg" min="0.01" step="0.01" value="<?= form_value($state, 'weight_kg') ?>" required><?= form_error($state, 'weight_kg') ?></div><div class="col-12"><label for="book-description">Package description</label><textarea class="form-control" id="book-description" name="package_description" required><?= form_value($state, 'package_description') ?></textarea><?= form_error($state, 'package_description') ?></div><?php foreach (['length_cm' => 'Length (cm)','width_cm' => 'Width (cm)','height_cm' => 'Height (cm)'] as $field => $label): ?><div class="col-md-4"><label for="book-<?= e($field) ?>"><?= e($label) ?></label><input class="form-control" type="number" id="book-<?= e($field) ?>" name="<?= e($field) ?>" min="0" step="0.01" value="<?= form_value($state, $field) ?>"></div><?php endforeach; ?><div class="col-md-6"><label for="book-value">Declared value (NGN)</label><input class="form-control" type="number" id="book-value" name="declared_value" min="0" step="0.01" value="<?= form_value($state, 'declared_value', '0') ?>"></div><div class="col-md-6 d-flex align-items-end gap-4 pb-3"><div class="form-check"><input class="form-check-input" type="checkbox" id="book-fragile" name="is_fragile" value="1"><label class="form-check-label" for="book-fragile">Fragile item</label></div><div class="form-check"><input class="form-check-input" type="checkbox" id="book-packaging" name="packaging_required" value="1"><label class="form-check-label" for="book-packaging">Packaging required</label></div></div><div class="col-12"><button class="easy-btn" type="submit" <?= count($addresses) < 2 ? 'disabled' : '' ?>><i class="bi bi-arrow-right"></i> Calculate and create booking</button><a class="ms-3" href="<?= e(url('calculator.php')) ?>">Calculate without booking</a></div></div></form></div></div></section>
<?php require dirname(__DIR__) . '/app/views/partials/public-footer.php'; ?>
